version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle

    steps:
      - checkout

      - run:
          name: install-npm@6.12.1
          command: sudo npm install -g npm@6.12.1

      - restore_cache:
          keys:
            - npm-dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: install-npm-package
          command: npm ci

      - save_cache:
          key: npm-dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./.npm

      - run:
          name: insltall-bunlder
          command: gem install bundler

      - restore_cache:
          keys:
            - bundle-{{ checksum "Gemfile.lock" }}

      - run:
          name: bundle-install
          command: bundle check || bundle install

      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: 'test/unit'
          command: bundle exec ruby test/test_my_calss.rb
